### ISSUE TITLE
Fork acknowledgement unexpectedly closes receiver

### ISSUE THREAD

**Issue by andybets** [EOSChronicleProject/eos-chronicle#11]
- I receive a BLOCK_COMPLETED msg for block 91767958
- I ack block 91767958
- I get a FORK msg: {"block_num: 91767957, "depth":1, 'last_irreversible": 91767647 ... }
- I ack block 91767956 (fork block minus 1)
- Chronicle receiver closes the connection because block 91767958 was already acknowledged
- Chronicle exits cleanly
- Chronicle reconnects and reverts to block 91767647 - so seems that previous ack (91767958) was lost

**Comment by cc32d9** [comment]
I got this, very rarely, mostly because of intensive forks:

```
Mar 28 21:35:43 strack chronicle-receiver[15727]: error 2021-03-28T21:35:43.592 chronicle receiver_plugin.cpp:1594      ack_block            ] Exporter acked block=111056701, but block=111056702 was already acknowledged                                                                                                 
Mar 28 21:35:43 strack chronicle-receiver[15727]: Exporter acked block below previuously acked one
Mar 28 21:35:43 strack systemd[1]: chronicle_receiver@wax.service: Main process exited, code=killed, status=11/SEGV
Mar 28 21:35:43 strack systemd[1]: chronicle_receiver@wax.service: Failed with result 'signal'.
```

need to find the time to investigate.
