### ISSUE TITLE
Malformed JSON in sample output

### ISSUE THREAD

**Issue by andybets** [EOSChronicleProject/eos-chronicle#2]
Thanks for the great project!

I made a smaller sample for testing parsing:
```head -n 1000000 chronicle_ws_output.json > testdata.json```

...then the following (in Python) seems to return a section which is malformed:
```
with open('testdata.json') as f:
    s = f.read()
s = s.replace('\n\n', ',\n')
s = '[' + s + ']'
return s[4262000:4263000]
```
e.g. ```"errors" : [ "Cannot decode table row for eosvegasjack: secrets - unknown type \"secrets\"" ], "primary_key" : "?, "scope" : "eosvegasjack", "table" : "secrets", "where" : "table_row_update" }```

**Comment by cc32d9** [comment]
The output file is not a correct JSON: it's a sequence of JSON objects separated by double newline. 

Also I made a new dump file at the day of the release, so maybe the one you were looking at was corrupted.

**Comment by andybets** [comment]
Thanks. It was one of the JSON objects which was malformed, but I haven't seen that in testing the software itself.
